In [158]:
import pandas as pd
import numpy as np
from PIL import Image
import cv2
import re

In [159]:
df = pd.read_csv("C:\\Users\\shyam\\OneDrive\\Datssets\\train.csv")
file_path = "C:\\Users\\shyam\\OneDrive\\Datssets\\{}"
df.head()

image:FILE  category
0  train/cat/Sphynx_159_jpg.rf.022528b23ac690c34a...         0
1  train/cat/Persian_139_jpg.rf.0e67f7e0a76dc49d0...         0
2  train/cat/Bengal_150_jpg.rf.05c93a40014062c5ae...         0
3  train/cat/Bombay_140_jpg.rf.15757f698af74453f3...         0
4  train/cat/Persian_128_jpg.rf.16da80c477d1ca2bc...         0

In [160]:
def pathConverter(df,pur):
    for dir in df['image:FILE']:
        rep = re.sub(f'{pur}/cat/',f'{pur}//cat//',dir)
        if rep == dir :
            df.replace(dir,re.sub(f'{pur}/dog/',f'{pur}//dog//',dir),inplace=True)
        else :
            df.replace(dir,re.sub(f'{pur}/cat/',f'{pur}//cat//',dir),inplace =True)
   

In [161]:
pathConverter(df,'train')
df['image:FILE'].head()

0    train//cat//Sphynx_159_jpg.rf.022528b23ac690c3...
1    train//cat//Persian_139_jpg.rf.0e67f7e0a76dc49...
2    train//cat//Bengal_150_jpg.rf.05c93a40014062c5...
3    train//cat//Bombay_140_jpg.rf.15757f698af74453...
4    train//cat//Persian_128_jpg.rf.16da80c477d1ca2...
Name: image:FILE, dtype: object

In [162]:
def splitter(df):
    images = []
    class_label = df['category']
    for dir in df['image:FILE']:
        image = cv2.imread(f"C:\\Users\\shyam\\OneDrive\\Datssets\\{dir}")
        image = cv2.resize(image,(120,120))
        gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
        x = gray_image.flatten()
        images.append(x)
    X = np.array(images)
#np.hstack([arr_train,np.array(class_label)])
    y = np.array(class_label)
    return (X,y)
 

In [163]:
X_train,y_train = splitter(df) 

In [164]:
X_train.shape,y_train.shape

((275, 14400), (275,))

In [165]:
from sklearn.linear_model import LogisticRegression

In [166]:
lreg = LogisticRegression(max_iter=14400)

In [167]:
lreg.fit(X_train,y_train)

LogisticRegression(max_iter=14400)

In [168]:
#lreg.score(X_train,y_train)

In [169]:
image = cv2.imread('cat_test.jpeg')

In [170]:
sizimage = cv2.resize(image,(120,120))
grayimage = cv2.cvtColor(sizimage,cv2.COLOR_BGR2GRAY)
img_array = grayimage.flatten()
in_img = np.array(img_array)
lreg.predict([in_img])

array([0], dtype=int64)

In [171]:
df = pd.read_csv("C:\\Users\\shyam\\OneDrive\\Datssets\\val.csv")
df.head()

image:FILE  category
0  val/cat/Persian_13_jpg.rf.dd6ccb81649242fcc8a2...         0
1  val/cat/Birman_137_jpg.rf.dc638a7840b71bfdcc9d...         0
2  val/cat/Siamese_142_jpg.rf.de98806682118bd0281...         0
3  val/cat/Birman_163_jpg.rf.de852821da3d65ebd262...         0
4  val/cat/Bengal_141_jpg.rf.e656908b712d2cb13742...         0

In [172]:
pathConverter(df,'val')
df.head()

image:FILE  category
0  val//cat//Persian_13_jpg.rf.dd6ccb81649242fcc8...         0
1  val//cat//Birman_137_jpg.rf.dc638a7840b71bfdcc...         0
2  val//cat//Siamese_142_jpg.rf.de98806682118bd02...         0
3  val//cat//Birman_163_jpg.rf.de852821da3d65ebd2...         0
4  val//cat//Bengal_141_jpg.rf.e656908b712d2cb137...         0

In [174]:
X_test,y_test = splitter(df)

In [175]:
X_test.shape,y_test.shape

((70, 14400), (70,))

In [176]:
lreg.predict(X_test)

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1], dtype=int64)

In [177]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int64)

In [178]:
KNN.predict(X_test)

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1], dtype=int64)

In [179]:
KNN.score(X_test,y_test)

0.6714285714285714

In [180]:
lreg.score(X_test,y_test)

0.5142857142857142